# Generated by Django 5.0.14 on 2025-04-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="balance",
        ),
    ]
